---
# configure_dotfiles: true
# configure_terminal: true
# configure_osx: true

# # Set to 'true' to configure the Dock via dockutil.
# configure_dock: false
# dockitems_remove: []
# # - Launchpad
# # - TV
# # - Podcasts
# # - 'App Store'
# dockitems_persist: []
# # - name: "Sublime Text"
# #   path: "/Applications/Sublime Text.app/"
# #   pos: 5

# configure_sudoers: false
# sudoers_custom_config: ''
# # Example:
# # sudoers_custom_config: |
# #   # Allow users in admin group to use sudo with no password.
# #   %admin ALL=(ALL) NOPASSWD: ALL

# dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
# dotfiles_repo_accept_hostkey: true
# dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
# dotfiles_files:
#   - .zshrc
#   - .gitignore
#   - .inputrc
#   - .osx
#   - .vimrc

homebrew_installed_packages:
  - ansible
  # - asdf
  # - athenacli
  # - autoconf
  # - automake
  # - avrdude
  - awscli
  # - bash
  # - berkeley-db@5
  # - boost
  # - brotli
  # - c-ares
  # - ca-certificates
  # - cairo
  # - certifi
  # - cffi
  # - cmake
  # - confuse
  # - coreutils
  # - cowsay
  # - cryptography
  # - dbus
  # - docutils
  # - duckdb
  # - eksctl
  # - flac
  # - fontconfig
  # - freetype
  # - gcc
  # - gdbm
  # - gettext
  # - giflib
  # - gimme-aws-creds
  - git
  # - glab
  # - glances
  # - glib
  # - gmp
  # - gnutls
  # - graphite2
  # - harfbuzz
  - helm
  # - hidapi
  # - highlight
  # - httpie
  # - hwloc
  # - icu4c
  # - iperf
  # - iperf3
  # - isl
  # - jira-cli
  # - jpeg-turbo
  - jq
  # - k2tf
  - k9s
  # - keyring
  # - krb5
  # - kubernetes-cli
  # - lame
  # - lazydocker
  # - lazygit
  # - libevent
  # - libftdi
  # - libgcrypt
  # - libgpg-error
  # - libidn2
  # - libmaxminddb
  # - libmpc
  # - libnghttp2
  # - libnghttp3
  # - libogg
  # - libpng
  # - libpq
  # - librtlsdr
  # - libsmi
  # - libsndfile
  # - libsodium
  # - libsoxr
  # - libssh
  # - libtasn1
  # - libtiff
  # - libtool
  # - libunistring
  # - libusb
  # - libusb-compat
  # - libuv
  # - libvorbis
  # - libwebsockets
  # - libx11
  # - libxau
  # - libxcb
  # - libxdmcp
  # - libxext
  # - libxrender
  # - libyaml
  # - liquibase
  # - little-cms2
  # - lua
  # - lz4
  # - lzo
  # - m
  # - mkcert- mpdecimal
  # - mpfr
  # - mpg123
  # - ncurses
  # - nettle
  # - nmap
  # - p11-kit
  # - pcre2
  # - perl
  # - pgcli
  # - pixman
  # - pkg-config
  # - pmix
  # - pulseaudio
  # - pycparser
  # - pyenv
  # - python-certifi
  # - python-cryptography
  # - python-packaging
  # - python@3.13
  # - python@3.9
  # - rclone
  # - readline
  # - rtl_433
  # - ruby
  # - soapyrtlsdr
  # - soapysdr
  # - speexdsp
  # - sphinx-doc
  # - sqlite
  # - telnet
  # - terraform
  - tmux
  # - uhd
  # - unbound
  # - unixodbc
  # - utf8proc
  # - watch
  # - wgcf
  # - wget
  # - wireguard-go
  # - wireguard-tools
  # - wireshark
  # - wrk
  # - xorgproto
  # - xz
  # - yq
  # - zsh-history-substring-search
  # - zstd

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # - android-file-transfer
  # - android-studio
  # - balenaetcher
  # - betterdisplay
  - brave-browser
  # - caffeine
  # - calibre
  - clipy
  # - cloudflare-warp
  # - code-composer-studio
  # - cubicsdr
  - datagrip
  # - docker
  # - fritzing
  # - godot
  # - gqrx
  # - grandperspective
  # - hoppscotch
  # - intellij-idea-ce
  # - macspice
  # - mqtt-explorer
  # - netspot
  # - numi
  # - openemu
  - plex
  # - protonvpn
  # - pycharm-ce
  # - qlcolorcode
  # - qlmarkdown
  # - qlstephen
  # - quicklook-json
  # - rar
  # - rectangle
  # - sketchup
  # - spotify
  # - steam
  # - temurin@8
  # - temurin8
  # - the-unarchiver
  # - transmission
  # - uniflash
  # - vagrant
  # - virtualbox
  # - visual-studio-code
  # - vlc
  # - warp
  # - wireshark
  # - zerotier-one

# # See `geerlingguy.mas` role documentation for usage instructions.
# mas_installed_apps: []
# mas_email: ""
# mas_password: ""

# osx_script: "~/.osx --no-restart"

# # Install packages from other package managers.
# # Note: You are responsible for making sure the required package managers are
# # installed, eg. through homebrew.
# composer_packages: []
# # - name: drush
# #   state: present # present/absent, default: present
# #   version: "^8.1" # default: N/A
# gem_packages: []
# # - name: bundler
# #   state: present # present/absent/latest, default: present
# #   version: "~> 1.15.1" # default: N/A
# npm_packages: []
# # - name: webpack
# #   state: present # present/absent/latest, default: present
# #   version: "^2.6" # default: N/A
# pip_packages: []
# # - name: mkdocs
# #   state: present # present/absent/latest, default: present
# #   version: "0.16.3" # default: N/A

# # Glob pattern to ansible task files to run after all other tasks are finished.
# post_provision_tasks: []